### ISSUE TITLE
Launching the poc_pipeline takes a lot of CPU

### ISSUE THREAD

**Issue by RemiFabre** [pollen-robotics/reachy_2023#180]
Some ideas:
* Check outliers (SpatialYolo? GraspCNN?).
* Maybe disable Gazebo client ?
* Check GPU usage.

**Comment by SteveNguyen** [comment]
fake_gz_interface and dynamic_state_router eat too much cpu for no reason (other than just being pure python nodes). They can "easily" be rewritten, ideally in Rust, but at least in cpp.

**Comment by cdussieux** [comment]
using yolo on cpu just uses 10 full thread out of 16 on my computer
i will test it on gpu

**Comment by cdussieux** [comment]
We should close this issue s there things has been done on this matter for poc_grasping
change full stream mode to cherry pick images and process only when required
reduce yolo detection framerate
if you want to improve performance to a new level, simply run yolo on gpu

issues pointed out by @SteveNguyen must be adressed in repo https://github.com/pollen-robotics/reachy_2023

**Comment by RemiFabre** [comment]
Post refacto, stuff is fast. When using CUDA it's even better. gg wp
