### ISSUE TITLE
Config file not found when launching bringup

### ISSUE THREAD

**Issue by PositiveBeat** [pollen-robotics/reachy_2023#246]
When running `ros2 launch reachy_bringup reachy.launch.py  fake:=true start_rviz:=true` I get the error:
```
[ERROR] [launch]: Caught exception in launch (see debug for traceback): [Errno 2] No such file or directory: '/home/<user>/.reachy.yaml'
```

The missing config file is here: `./src/reachy_2023/reachy_utils/reachy_utils/files/.reachy.yaml` (relative to `reachy_ws` folder).

Will you change the path or add instructions to move the config to the home folder?

Thank you!

**Comment by RemiFabre** [comment]
Good catch!
The following command was added to the README:
```
cp ~/reachy_ws/src/reachy_2023/reachy_utils/reachy_utils/files.reachy.yaml ~/
```
